server:
  port: 8081
  tomcat:
    threads:
      max: 1000 # 생성할 수 있는 thread의 총 개수
      min-spare: 10 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 8000 # 수립가능한 connection의 총 개수
    accept-count: 100 # 작업큐의 사이즈
    connection-timeout: 20000 # timeout 판단 기준 시간, 20초

spring:

  profiles:
    active:
    include: secret

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/twalk
    platform: postgres
    username: postgres
    password: qpqpqp0614
    hikari:
    minimumIdle: 2
    maximumPoolSize: 100000 # 다중 유저 처리를 위해 증가시켜줌, 최대 연결 수로 세션이 해제되는 시간을 가지는 세션도 있으므로 넉넉히 설정
    idleTimeout: 120000
    connectionTimeout: 300000
    leakDetectionThreshold: 300000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  servlet.multipart.max-file-size: 500MB
  servlet.multipart.max-request-size: 500MB

  http.encoding.charset: UTF-8
  http.encoding.enabled: true
  http.encoding.force: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

upload:
  image:
    location: src/main/prodmedia/image/

default :
  image :
    address : "src/main/prodmedia/image/default/default.PNG"
